language: go

go:
  - "1.11.x"

install:
  - CGO_ENABLED=0 GOOS=linux  GOARCH=amd64 go build -o uuidgen_linux_amd64 main.go
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o uuidgen_darwin_amd64 main.go

script:
  - uuidgen -h
  - uuidgen
  - uuidgen -n 10 -upper

deploy:
  provider: releases
  user: ${GITHUB_USERNAME}
  password: ${GITHUB_PASSWORD}
  file: 
    - uuidgen_linux_amd64
    - uuidgen_darwin_amd64
  skip_cleanup: true
  on:
    tags: true
